/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Logica.ClienteSimple;
import Logica.LicenciaConducir;
import ClasesMaestras.Persona1;
import ClasesMaestras.Vehiculo1;
import Excepciones.SinDigitos;
import Excepciones.TextVacio;
import Excepciones.CaractInicio;
import Excepciones.SinLetras;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class Alquiler extends javax.swing.JFrame {
    String nombre, numTel, fechaReg, tipoLic, fechaVenc;
    int idCliente, dni, num;
    boolean ant;
    
    private Vehiculo1 vehiculoSeleccionado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Alquiler.class.getName());

    /**
     * Creates new form Alquiler
     */
    public Alquiler() {
        initComponents();
    }
    
    public Alquiler(Vehiculo1 vehiculo) {
        initComponents();
        this.vehiculoSeleccionado = vehiculo;
    }
    
    public void RevisionTextoDig(String cad) throws SinDigitos{
        int cont=0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isDigit(c)){
                cont++;
            }
        }
        if(cont>0){
            throw new SinDigitos("Este texto no puede llevar numeros.");
        }
    }
    
    public void RevisionTextoLet(String cad) throws SinLetras{
        int let = 0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isLetter(c)){
                let++;
            }
        }
        if(let>0){
            throw new SinLetras("Este texto no puede llevar letras.");
        }
    }
    
    public void RevisionTextoVacio(String cad) throws TextVacio{
        if(cad.length() == 0){
            throw new TextVacio("Escriba algo para ingresar...");
        }
    }
    
    public void Comienzo(String cad) throws CaractInicio{
        char c = cad.charAt(0);
        char t = ' ';
        if(c == t){
            throw new CaractInicio("Caracter de inicio vacio.");
        }
    }
    
    public void RevisionTextoEspeciales(String texto) throws IllegalArgumentException {  
        for (int i = 0; i < texto.length(); i++) {
            char c = texto.charAt(i);
            
            if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
                throw new IllegalArgumentException("Error: Se encontró un carácter especial '" + c + "' en la cadena.");
            }
        }
        
        System.out.println("La cadena '" + texto + "' es válida y está limpia.");
    }
    
    public void FechaFormato(String cad) throws DateTimeParseException{
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String fechaValidada = "";
        LocalDate.parse(cad, formato);
        Date.parse(cad);
        if(fechaValidada == cad){
            throw new DateTimeParseException("Error: El formato de la fecha es incorrecto.", cad, 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        T_Nombre = new javax.swing.JTextField();
        T_IDCliente = new javax.swing.JTextField();
        T_Telefono = new javax.swing.JTextField();
        T_DNI = new javax.swing.JTextField();
        T_Numero = new javax.swing.JTextField();
        T_Tipo = new javax.swing.JTextField();
        T_Fecha_Vencimiento = new javax.swing.JTextField();
        Ingresar_Alquiler = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        T_Fecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        B_SI = new javax.swing.JButton();
        B_NO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Alquiler");

        jLabel2.setText("Nombre");

        jLabel3.setText("IdCliente");

        jLabel4.setText("Telefono");

        jLabel5.setText("DNI");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Datos de la licencia");

        jLabel7.setText("Número");

        jLabel8.setText("Tipo");

        jLabel9.setText("Fecha de vencimiento");

        T_Nombre.addActionListener(this::T_NombreActionPerformed);

        T_IDCliente.addActionListener(this::T_IDClienteActionPerformed);

        T_Telefono.addActionListener(this::T_TelefonoActionPerformed);

        T_DNI.addActionListener(this::T_DNIActionPerformed);

        T_Numero.addActionListener(this::T_NumeroActionPerformed);

        T_Tipo.addActionListener(this::T_TipoActionPerformed);

        T_Fecha_Vencimiento.setText("dd/mm/aaaa");
        T_Fecha_Vencimiento.addActionListener(this::T_Fecha_VencimientoActionPerformed);

        Ingresar_Alquiler.setText("Ingresar alquiler");
        Ingresar_Alquiler.addActionListener(this::Ingresar_AlquilerActionPerformed);

        jButton2.setText("Salir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel10.setText("Fecha");

        T_Fecha.setText("dd/mm/aaaa");
        T_Fecha.addActionListener(this::T_FechaActionPerformed);

        jLabel11.setText("Antecedentes");

        B_SI.setText("SI");
        B_SI.addActionListener(this::B_SIActionPerformed);

        B_NO.setText("NO");
        B_NO.addActionListener(this::B_NOActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(B_SI)
                .addGap(40, 40, 40)
                .addComponent(B_NO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_SI)
                    .addComponent(B_NO))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                                .addComponent(Ingresar_Alquiler))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(T_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(T_IDCliente)
                                    .addComponent(T_Telefono)
                                    .addComponent(T_DNI)
                                    .addComponent(T_Numero)
                                    .addComponent(T_Tipo)
                                    .addComponent(T_Fecha)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(T_Fecha_Vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel6)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(T_IDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(T_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(T_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(T_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(T_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(T_Fecha_Vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2)
                                            .addComponent(Ingresar_Alquiler)))
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel8)))
                    .addComponent(jLabel7))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_AlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_AlquilerActionPerformed
        try {
            // 1. Extraemos los textos de la interfaz AL MOMENTO DE HACER CLIC
            String txtNombre = T_Nombre.getText();
            String txtID = T_IDCliente.getText();
            String txtTel = T_Telefono.getText();
            String txtDNI = T_DNI.getText();
            String txtFechaReg = T_Fecha.getText();
            String txtNumLic = T_Numero.getText();
            String txtTipoLic = T_Tipo.getText();
            String txtFechaVenc = T_Fecha_Vencimiento.getText();

            RevisionTextoVacio(txtNombre);
            RevisionTextoDig(txtNombre);
            Comienzo(txtNombre);
            
            RevisionTextoVacio(txtID);
            RevisionTextoLet(txtID);
            
            RevisionTextoVacio(txtTel);
            RevisionTextoLet(txtTel);
            
            RevisionTextoVacio(txtDNI);
            RevisionTextoLet(txtDNI);
            
            RevisionTextoVacio(txtNumLic);
            RevisionTextoLet(txtNumLic);
            
            FechaFormato(txtFechaReg);
            FechaFormato(txtFechaVenc);

            idCliente = Integer.parseInt(txtID);
            dni = Integer.parseInt(txtDNI);
            num = Integer.parseInt(txtNumLic);

            LicenciaConducir lc = new LicenciaConducir();
            lc.setNum(num);
            lc.setFechaVencimiento(txtFechaVenc);
            lc.setTipoLic(txtTipoLic);
            
            ClienteSimple per = new ClienteSimple(); 
            per.setIdCliente(idCliente);
            per.setNombre(txtNombre);
            per.setNumTelefono(txtTel);
            per.setFechaRegistro(txtFechaReg);
            per.setDni(dni);
            per.setAntecedente(ant); 
            per.setLicencia(lc);

            
            MovTransaccionales.ArregloCliente1 contenedorClientes = new MovTransaccionales.ArregloCliente1();

            try { 
            // 2. Usamos el nombre real del método (cargarClientes)
            Persistencia.PersistenciaCliente.cargarClientes(contenedorClientes); 
            } catch (Exception e) {
               System.out.println("No se pudo cargar o archivo nuevo.");
            }
        
            contenedorClientes.agregarCliente(per);
        
            Persistencia.PersistenciaCliente.guardarClientes(contenedorClientes);
            if (vehiculoSeleccionado != null) {
    Persistencia.VehiculoPersistencia<Vehiculo1> persistenciaVeh = new Persistencia.VehiculoPersistencia<>();
    ArrayList<Vehiculo1> todosLosVehiculos = new ArrayList<>();
    persistenciaVeh.RecuperarVehiculos(todosLosVehiculos);

    Vehiculo1 vehiculoActualizado = null;   // <-- nuevo
    for (Vehiculo1 v : todosLosVehiculos) {
        if (v.getNroSerie() == vehiculoSeleccionado.getNroSerie()) {
            v.setAlq(true);
            v.setIdClienteAlquiler(idCliente);
            v.setFechaAlquiler(txtFechaReg);
            vehiculoActualizado = v;         // <-- nuevo
            break;
        }
    }

    persistenciaVeh.GuardarVehiculos(todosLosVehiculos);

    // NUEVO: registrar el alquiler en el historial (alquileres.dat)
        if (vehiculoActualizado != null) {
            Persistencia.AlquilerPersistencia persistenciaAlq = new Persistencia.AlquilerPersistencia();
            Logica.Nodo cabExistente = persistenciaAlq.RecuperarAlquiler();
            MovTransaccionales.ContenedorAlquiler contenedorAlq = new MovTransaccionales.ContenedorAlquiler();
            contenedorAlq.setCab(cabExistente);
            Logica.Alquiler nuevoAlquiler = new Logica.Alquiler(vehiculoActualizado, per, txtFechaReg);
            contenedorAlq.AgregarAlquiler(nuevoAlquiler);
                persistenciaAlq.GuardarAlquiler(contenedorAlq.getCab());
            }
        } else {
            System.out.println("Aviso: no se recibió el vehículo seleccionado; no se marcó como alquilado.");
        }
           

            // 6. Navegación a la ventana de confirmación
            AlquilerConfirmado ventanaConfirmacion = new AlquilerConfirmado();
            ventanaConfirmacion.setLocationRelativeTo(null);
            ventanaConfirmacion.setVisible(true);
            this.dispose();

        } catch (TextVacio | SinLetras | SinDigitos | CaractInicio | IllegalArgumentException | DateTimeParseException ex) {
            // Si AL MENOS UNA validación falla, atrapamos el error y mostramos tu mensaje
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Validación", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado. Verifique los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Ingresar_AlquilerActionPerformed

    private void T_IDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_IDClienteActionPerformed
        try{
            idCliente = Integer.parseInt(T_IDCliente.getText());
            RevisionTextoVacio(T_IDCliente.getText());
            RevisionTextoLet(T_IDCliente.getText());
            Comienzo(T_IDCliente.getText());
            RevisionTextoEspeciales(T_IDCliente.getText());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, "Error: Se encontró un carácter especial en la cadena.");
        }
    }//GEN-LAST:event_T_IDClienteActionPerformed

    private void T_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_NombreActionPerformed
        try{
            nombre = T_Nombre.getText();
            RevisionTextoDig(nombre);
            RevisionTextoVacio(nombre);
            Comienzo(nombre);
            RevisionTextoEspeciales(nombre);
        }catch(SinDigitos e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_NombreActionPerformed

    private void T_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_TelefonoActionPerformed
        try{
            numTel = T_Telefono.getText();
            RevisionTextoLet(numTel);
            RevisionTextoEspeciales(numTel);
            Comienzo(numTel);
            RevisionTextoVacio(numTel);
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_TelefonoActionPerformed

    private void T_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_DNIActionPerformed
        try{
            dni = Integer.parseInt(T_DNI.getText());
            RevisionTextoVacio(T_DNI.getText());
            RevisionTextoLet(T_DNI.getText());
            Comienzo(T_DNI.getText());
            RevisionTextoEspeciales(T_DNI.getText());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_DNIActionPerformed

    private void T_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_FechaActionPerformed
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try{
            fechaReg = T_Fecha.getText();
            RevisionTextoVacio(T_Fecha.getText());
            RevisionTextoLet(T_Fecha.getText());
            Comienzo(T_Fecha.getText());
            FechaFormato(T_Fecha.getText());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_FechaActionPerformed

    private void T_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_NumeroActionPerformed
        try{
        num = Integer.parseInt(T_Numero.getText());
        RevisionTextoVacio(T_Numero.getText());
        RevisionTextoLet(T_Numero.getText());
        Comienzo(T_Numero.getText());
        RevisionTextoEspeciales(T_Numero.getText());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_NumeroActionPerformed

    private void T_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_TipoActionPerformed
        try{
            tipoLic = T_Tipo.getText();
            RevisionTextoDig(nombre);
            RevisionTextoVacio(T_Numero.getText());
            Comienzo(T_Numero.getText());
            RevisionTextoEspeciales(T_Numero.getText());
        }catch(SinDigitos e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_TipoActionPerformed

    private void T_Fecha_VencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_Fecha_VencimientoActionPerformed
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try{
            fechaVenc = T_Fecha.getText();
            RevisionTextoVacio(T_Fecha.getText());
            RevisionTextoLet(T_Fecha.getText());
            Comienzo(T_Fecha.getText());
            FechaFormato(T_Fecha.getText());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(DateTimeParseException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_Fecha_VencimientoActionPerformed

    private void B_SIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SIActionPerformed
        ant = false;
    }//GEN-LAST:event_B_SIActionPerformed

    private void B_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_NOActionPerformed
        ant = true;
    }//GEN-LAST:event_B_NOActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SelecciónCategoria ventanaAnterior = new SelecciónCategoria();
        ventanaAnterior.setLocationRelativeTo(null);
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Alquiler().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_NO;
    private javax.swing.JButton B_SI;
    private javax.swing.JButton Ingresar_Alquiler;
    private javax.swing.JTextField T_DNI;
    private javax.swing.JTextField T_Fecha;
    private javax.swing.JTextField T_Fecha_Vencimiento;
    private javax.swing.JTextField T_IDCliente;
    private javax.swing.JTextField T_Nombre;
    private javax.swing.JTextField T_Numero;
    private javax.swing.JTextField T_Telefono;
    private javax.swing.JTextField T_Tipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
