/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.Moto;
import java.util.ArrayList;
import ClasesMaestras.Vehiculo1;
import Persistencia.VehiculoPersistencia; 
/**
 *
 * @author SEBASTIAN
 */
public class CatMotos<T extends Vehiculo1> extends javax.swing.JFrame {
    
    private final ArrayList<T> vehiculosEnTabla = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CatMotos.class.getName());

    /**
     * Creates new form CatMotos
     */
    public CatMotos() {
        initComponents();
        cargarDatosDelArchivo(); // LLAMADA FALTANTE AGREGADA
    }
    
    // MÉTODO FALTANTE AGREGADO PARA LEER EL DISCO DURO
    private void cargarDatosDelArchivo() {
        VehiculoPersistencia<Vehiculo1> persistencia = new VehiculoPersistencia<>();
        ArrayList<Vehiculo1> listaRecuperada = new ArrayList<>();
        
        try {
            // Deserializamos el archivo .dat
            persistencia.RecuperarVehiculos(listaRecuperada);
            
            // Enviamos la lista para pintar la tabla (casteo explícito requerido por tu genericidad)
            EscribirMoto((ArrayList<T>) listaRecuperada);
            
        } catch (Exception e) {
            System.err.println("Error al cargar las motos desde el archivo: " + e.getMessage());
        }
    }
    
    public void EscribirMoto(ArrayList<T> listaVehiculos) {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    //Se limpia la tabla por si ya tenía datos antes
    modelo.setRowCount(0);
    vehiculosEnTabla.clear();
    
    for (int i = 0; i < listaVehiculos.size(); i++) {
        T vehiculo = listaVehiculos.get(i);
        
        // Verificar si es una Moto y que no esté ya alquilada
        if (vehiculo instanceof Moto && !vehiculo.isAlq()) {
            modelo.addRow(new Object[]{ 
                ((Moto)vehiculo).getTipo(), 
                ((Moto)vehiculo).getCilindrada(), 
                ((Moto)vehiculo).getManillar(), 
                ((Moto)vehiculo).getEstacion()
            });
            vehiculosEnTabla.add(vehiculo);
        }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Motos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Cilindrada", "Manillar", "Estación"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Iniciar alquiler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(275, 275, 275)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SelecciónCategoria ventanaCategoria = new SelecciónCategoria();
    ventanaCategoria.setLocationRelativeTo(null);
    ventanaCategoria.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code hereAlquiler ventanaAlquiler = new Alquiler();
    int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            // Si es -1, mostramos un mensaje de alerta y detenemos la ejecución del botón
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione un vehículo de la tabla antes de iniciar el alquiler.", 
                "Aviso", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            T vehiculoSeleccionado = vehiculosEnTabla.get(filaSeleccionada);
            Alquiler ventanaAlquiler = new Alquiler(vehiculoSeleccionado);
            ventanaAlquiler.setLocationRelativeTo(null);
            ventanaAlquiler.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatMotos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
