/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import ClasesMaestras.Vehiculo1;
import Logica.Camion;

/**
 *
 * @author LENOVO
 */
public class EliminoCamión<T extends Vehiculo1> extends javax.swing.JFrame {
    ArrayList<T> listaVehiculos = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminoCamión.class.getName());

    /**
     * Creates new form EliminoCamión
     */
    public EliminoCamión() {
        initComponents();
    }
    
    public void EscribirCamión() {
    // Se obtiene el modelo de jTable1
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    //Se limpia la tabla por si ya tenía datos antes
    modelo.setRowCount(0);
    
        for (int i = 0; i < listaVehiculos.size(); i++) {
            T vehiculo = listaVehiculos.get(i);

            // 4. Verificar si es un Auto
            if (vehiculo instanceof Camion) {
                modelo.addRow(new Object[]{
                    ((Camion)vehiculo).getNroSerie(), 
                    ((Camion)vehiculo).getTipoRemolque(), 
                    ((Camion)vehiculo).getNumEjes(), 
                    ((Camion)vehiculo).getCargaNeta(), 
                    ((Camion)vehiculo).getAlq()
                });
            }
        }
    }
    
    private void eliminarDeLaListaLógica(int nroserie) {
        for (int i = 0; i < listaVehiculos.size(); i++) {
            T v = listaVehiculos.get(i);
            if (v instanceof Camion) {
                Camion cami = (Camion) v;
                if (cami.getNroSerie() == nroserie) { 
                    listaVehiculos.remove(i);
                    break;
                }
            }
        }
    }
    
    private void B_EliminarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
        //Se obtiene el índice de la fila que el usuario seleccionó (hizo clic)
        int filaSeleccionada = jTable1.getSelectedRow();

        //Se valida que realmente haya seleccionado algo (-1 significa que no hay selección)
        if (filaSeleccionada != -1) {

            //Pedir confirmación para evitar borrados accidentales
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "¿Estás seguro de que deseas eliminar este auto?", 
                    "Confirmar", 
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {

                //ELIMINAMOS DEL ARRAYLIST (Lógica)
                // Obtenemos un dato único para buscarlo (ej. la Placa, asumiendo que está en la columna 0)
                int nroserie = (int) modelo.getValueAt(filaSeleccionada, 0);
                eliminarDeLaListaLógica(nroserie); 

                //ELIMINAMOS DEL JTABLE (Vista)
                modelo.removeRow(filaSeleccionada);

                javax.swing.JOptionPane.showMessageDialog(this, "Auto eliminado con éxito.");
            }

        } else {
            // Si se intenta eliminar sin seleccionar nada, mostramos un aviso
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un auto en la tabla primero.");
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Eliminación de Camiones");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° serie", "Tipo de remolque", "N°ejes", "Carga Neta", "Alquiler"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(487, 487, 487)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EliminoCamión().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
