/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import ClasesMaestras.Vehiculo1;
import ClasesMaestras.Persona1;
import Persistencia.VehiculoPersistencia;
import Persistencia.PersistenciaCliente;
import MovTransaccionales.ArregloCliente1;
/**
 *
 * @author LENOVO
 */
public class FinalizarAlquiler<T extends Vehiculo1> extends javax.swing.JFrame {
    
    ArrayList<T> listaVehiculos = new ArrayList<>();
    ArregloCliente1 clientesCargados = new ArregloCliente1();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinalizarAlquiler.class.getName());

    /**
     * Creates new form FinalizarAlquiler
     */
    public FinalizarAlquiler() {
        initComponents();
        cargarVehiculosDesdeArchivo();
    }
    
    private void cargarVehiculosDesdeArchivo() {
        VehiculoPersistencia<T> persistencia = new VehiculoPersistencia<>();
        try {
            persistencia.RecuperarVehiculos(listaVehiculos);
        } catch (Exception e) {
            System.out.println("No se pudieron cargar los vehículos: " + e.getMessage());
        }
        try {
            PersistenciaCliente.cargarClientes(clientesCargados);
        } catch (Exception e) {
            System.out.println("No se pudieron cargar los clientes: " + e.getMessage());
        }
        EscribirAlquilados();
    }
    
    public void EscribirAlquilados() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        for (int i = 0; i < listaVehiculos.size(); i++) {
            T v = listaVehiculos.get(i);
            
            if (v.isAlq()) { 
                Persona1 cliente = clientesCargados.buscarCliente(v.getIdClienteAlquiler());
                String nombreCliente = (cliente != null) ? cliente.getNombre() : "Desconocido";
                String fechaAlquiler = v.getFechaAlquiler();

                modelo.addRow(new Object[]{
                    v.getNroSerie(),               
                    v.getClass().getSimpleName(),
                    nombreCliente,
                    fechaAlquiler
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Vehiculos alquilados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°Serie", "Vehiculo", "Nombre Cliente", "Fecha "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Registrar devolución");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Salir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MenuTrabajador menu = new MenuTrabajador();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada != -1) {
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "¿Confirmar la devolución de este vehículo?", 
                    "Registrar Devolución", 
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                try {
                    // Obtenemos el nroSerie de la tabla (Columna 0)
                    String valorCelda = modelo.getValueAt(filaSeleccionada, 0).toString();
                    int nroSerieSeleccionado = Integer.parseInt(valorCelda);

                    // Buscamos el vehículo y cambiamos su estado
                    for (T v : listaVehiculos) {
                        if (v.getNroSerie() == nroSerieSeleccionado) {
                            v.setAlq(false); // Liberamos el vehículo
                            break;
                        }
                    }
                    
                   VehiculoPersistencia<T> persistencia = new VehiculoPersistencia<>();
                    persistencia.GuardarVehiculos(listaVehiculos);
                    Persistencia.AlquilerPersistencia persistenciaAlq = new Persistencia.AlquilerPersistencia();
                    Logica.Nodo cabAlquileres = persistenciaAlq.RecuperarAlquiler();
                    Logica.Nodo actual = cabAlquileres;
                    String fechaHoy = java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                    while (actual != null) {
                        Logica.Alquiler a = actual.dato;
                        if (a.isActivo() && a.getVeh().getNroSerie() == nroSerieSeleccionado) {
                            a.setFechaFin(fechaHoy);
                            break;
                        }
                    actual = actual.sig;
                    }
                    persistenciaAlq.GuardarAlquiler(cabAlquileres);

                    modelo.removeRow(filaSeleccionada);
                    javax.swing.JOptionPane.showMessageDialog(this, "Devolución registrada exitosamente.");
                    
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage());
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un alquiler de la tabla.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
