/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Excepciones.CaractInicio;
import Excepciones.SinDigitos;
import Excepciones.SinLetras;
import Excepciones.TextVacio;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class IngresoCamion extends javax.swing.JFrame {
    int nroejes; 
    String tipoRemol;
    Double cargaN;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoCamion.class.getName());

    /**
     * Creates new form IngresoCamion
     */
    public IngresoCamion() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(139, 69, 19));
    }
    
    public void RevisionTextoDig(String cad) throws SinDigitos{
        int cont=0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isDigit(c)){
                cont++;
            }
        }
        if(cont>0){
            throw new SinDigitos("Este texto no puede llevar numeros.");
        }
    }
    
    public void RevisionTextoLet(String cad) throws SinLetras{
        int let = 0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isLetter(c)){
                let++;
            }
        }
        if(let>0){
            throw new SinLetras("Este texto no puede llevar letras.");
        }
    }
    
    public void RevisionTextoVacio(String cad) throws TextVacio{
        if(cad.length() == 0){
            throw new TextVacio("Escriba algo para ingresar...");
        }
    }
    
    public void Comienzo(String cad) throws CaractInicio{
        char c = cad.charAt(0);
        char t = ' ';
        if(c == t){
            throw new CaractInicio("Caracter de inicio vacio.");
        }
    }
    
    public void RevisionTextoEspeciales(String texto) throws IllegalArgumentException {  
        for (int i = 0; i < texto.length(); i++) {
            char c = texto.charAt(i);
            
            if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
                throw new IllegalArgumentException("Error: Se encontró un carácter especial '" + c + "' en la cadena.");
            }
        }
        
        System.out.println("La cadena '" + texto + "' es válida y está limpia.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T_NroEjes = new javax.swing.JTextField();
        T_Carga = new javax.swing.JTextField();
        T_TipoR = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24));
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del Camión");

        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Numero de ejes");

        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Carga Neta");

        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Tipo de remolque");

        T_NroEjes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_NroEjesActionPerformed(evt);
            }
        });

        T_Carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_CargaActionPerformed(evt);
            }
        });

        T_TipoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_TipoRActionPerformed(evt);
            }
        });

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoSalir.png")));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoSiguiente.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T_NroEjes, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(T_Carga)
                    .addComponent(T_TipoR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T_NroEjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(T_Carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T_TipoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if(T_NroEjes.getText().isEmpty() || T_Carga.getText().isEmpty() || T_TipoR.getText().isEmpty()) {
                throw new TextVacio("Todos los campos son obligatorios.");
            }
            
            int ejes = Integer.parseInt(T_NroEjes.getText());
            double carga = Double.parseDouble(T_Carga.getText());
            String tipoRemolque = T_TipoR.getText();
            
           IngresoDatosGenerales ventanaDatos = new IngresoDatosGenerales();
            ventanaDatos.setTipoVehiculo("CAMION");
            ventanaDatos.setDatosCamion(ejes, carga, tipoRemolque);
            ventanaDatos.setLocationRelativeTo(null);
            ventanaDatos.setVisible(true);
            this.dispose();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número de ejes y Carga deben ser valores numéricos.");
        } catch (TextVacio e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al avanzar: " + e.getMessage());
        }
    }

    private void T_NroEjesActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            nroejes = Integer.parseInt(T_NroEjes.getText());
            RevisionTextoLet(T_NroEjes.getText());
            RevisionTextoVacio(T_NroEjes.getText());
            Comienzo(T_NroEjes.getText());
            RevisionTextoEspeciales(T_NroEjes.getText());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void T_CargaActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            cargaN = Double.parseDouble(T_Carga.getText());
            RevisionTextoLet(T_Carga.getText());
            RevisionTextoVacio(T_Carga.getText());
            Comienzo(T_Carga.getText());
            RevisionTextoEspeciales(T_Carga.getText());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void T_TipoRActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            tipoRemol = T_TipoR.getText();
            RevisionTextoDig(tipoRemol);
            RevisionTextoVacio(T_Carga.getText());
            Comienzo(T_Carga.getText());
            RevisionTextoEspeciales(T_Carga.getText());
        }catch(SinDigitos e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        IngresarVehiculo ventanaSeleccion = new IngresarVehiculo();
        ventanaSeleccion.setLocationRelativeTo(null);
        ventanaSeleccion.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoCamion().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField T_Carga;
    private javax.swing.JTextField T_NroEjes;
    private javax.swing.JTextField T_TipoR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration
}
