/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Excepciones.CaractInicio;
import Excepciones.SinDigitos;
import Excepciones.SinLetras;
import Excepciones.TextVacio;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class IngresoAuto extends javax.swing.JFrame {
    String marca, modelo, placa;
    int nroPas;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoAuto.class.getName());

    /**
     * Creates new form IngresoAuto
     */
    public IngresoAuto() {
        initComponents();
    }
    
    public void RevisionTextoDig(String cad) throws SinDigitos{
        int cont=0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isDigit(c)){
                cont++;
            }
        }
        if(cont>0){
            throw new SinDigitos("Este texto no puede llevar numeros.");
        }
    }
    
    public void RevisionTextoLet(String cad) throws SinLetras{
        int let = 0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isLetter(c)){
                let++;
            }
        }
        if(let>0){
            throw new SinLetras("Este texto no puede llevar letras.");
        }
    }
    
    public void RevisionTextoVacio(String cad) throws TextVacio{
        if(cad.length() == 0){
            throw new TextVacio("Escriba algo para ingresar...");
        }
    }
    
    public void Comienzo(String cad) throws CaractInicio{
        char c = cad.charAt(0);
        char t = ' ';
        if(c == t){
            throw new CaractInicio("Caracter de inicio vacio.");
        }
    }
    
    public void RevisionTextoEspeciales(String texto) throws IllegalArgumentException {  
        for (int i = 0; i < texto.length(); i++) {
            char c = texto.charAt(i);
            
            if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
                throw new IllegalArgumentException("Error: Se encontró un carácter especial '" + c + "' en la cadena.");
            }
        }
        
        System.out.println("La cadena '" + texto + "' es válida y está limpia.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        T_Marca = new javax.swing.JTextField();
        T_Modelo = new javax.swing.JTextField();
        T_Placa = new javax.swing.JTextField();
        T_NumPasaj = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Datos del Auto");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Placa");

        jLabel5.setText("Numero de pasajeros");

        T_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_MarcaActionPerformed(evt);
            }
        });

        T_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_ModeloActionPerformed(evt);
            }
        });

        T_Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_PlacaActionPerformed(evt);
            }
        });

        T_NumPasaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_NumPasajActionPerformed(evt);
            }
        });

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(T_NumPasaj, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(T_Marca, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(T_Modelo)
                                    .addComponent(T_Placa))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(T_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T_NumPasaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validamos que los campos no estén vacíos
            if(T_Marca.getText().isEmpty() || T_Modelo.getText().isEmpty() || T_Placa.getText().isEmpty()) {
                throw new TextVacio("Todos los campos son obligatorios.");
            }
            
            // 2. Instanciamos la siguiente pantalla
            IngresoDatosGenerales ventanaDatos = new IngresoDatosGenerales();
            ventanaDatos.setDatosPrevios(T_Marca.getText(), T_Modelo.getText(), T_Placa.getText());
            ventanaDatos.setNumPasajeros(Integer.parseInt(T_NumPasaj.getText()));
            ventanaDatos.setLocationRelativeTo(null);
            ventanaDatos.setVisible(true);
            this.dispose();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de pasajeros debe ser un valor numérico.");
        } catch (TextVacio e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al avanzar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        IngresarVehiculo ventanaSeleccion = new IngresarVehiculo();
        ventanaSeleccion.setLocationRelativeTo(null);
        ventanaSeleccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_MarcaActionPerformed
        try{
            marca = T_Marca.getText();
            RevisionTextoDig(marca);
            RevisionTextoVacio(marca);
            Comienzo(marca);
            RevisionTextoEspeciales(marca);
        }catch(SinDigitos e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_MarcaActionPerformed

    private void T_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_ModeloActionPerformed
        try{
            modelo = T_Modelo.getText();
            RevisionTextoDig(modelo);
            RevisionTextoVacio(modelo);
            Comienzo(modelo);
            RevisionTextoEspeciales(modelo);
        }catch(SinDigitos e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_ModeloActionPerformed

    private void T_PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_PlacaActionPerformed
        try{
            placa = T_Modelo.getText();
            RevisionTextoVacio(placa);
            Comienzo(placa);
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_PlacaActionPerformed

    private void T_NumPasajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_NumPasajActionPerformed
        try{
            nroPas = Integer.parseInt(T_NumPasaj.getText());
            RevisionTextoLet(T_NumPasaj.getText());
            RevisionTextoVacio(T_NumPasaj.getText());
            Comienzo(T_NumPasaj.getText());
            RevisionTextoEspeciales(T_NumPasaj.getText());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_NumPasajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoAuto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T_Marca;
    private javax.swing.JTextField T_Modelo;
    private javax.swing.JTextField T_NumPasaj;
    private javax.swing.JTextField T_Placa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
