/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Excepciones.TextVacio;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import Persistencia.VehiculoPersistencia;
import ClasesMaestras.Vehiculo1;
import Logica.Auto;
import Logica.Scooter;
import Logica.Bicicleta;
import Logica.Moto;
import Logica.Camion;

/**
 *
 * @author SEBASTIAN
 */
public class IngresoDatosGenerales extends javax.swing.JFrame {
    // Indica qué tipo de vehículo se está registrando.
    // Valores esperados: "AUTO", "SCOOTER", "BICICLETA", "MOTO", "CAMION"
    private String tipoVehiculo = "AUTO";

    // ---- Datos específicos de Auto ----
    private String marca, modelo, placa;
    private int numPasajeros;

    // ---- Datos específicos de Scooter ----
    private boolean plegable, bluetoothScooter;
    private double diametroRuedas;
    private int porcBateriaScooter;
    private String marcaScooter;

    // ---- Datos específicos de Bicicleta ----
    private boolean tipoMotorBici, pantallaBici;
    private int tipoBici;

    // ---- Datos específicos de Moto ----
    private int tipoMoto, manillarMoto, cilindradaMoto;

    // ---- Datos específicos de Camión ----
    private int numEjesCamion;
    private double cargaNetaCamion;
    private String tipoRemolqueCamion;

    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }

    public void setDatosPrevios(String marca, String modelo, String placa) {
        this.marca = marca;
        this.modelo = modelo;
        this.placa = placa;
    }
    public void setNumPasajeros(int numPasajeros) {
        this.numPasajeros = numPasajeros;
    }

    public void setDatosScooter(boolean plegable, boolean bluetooth, double diametroRuedas, int porcBateria, String marca) {
        this.plegable = plegable;
        this.bluetoothScooter = bluetooth;
        this.diametroRuedas = diametroRuedas;
        this.porcBateriaScooter = porcBateria;
        this.marcaScooter = marca;
    }

    public void setDatosBicicleta(boolean tipoMotor, boolean pantalla, int tipo) {
        this.tipoMotorBici = tipoMotor;
        this.pantallaBici = pantalla;
        this.tipoBici = tipo;
    }

    public void setDatosMoto(int tipo, int manillar, int cilindrada) {
        this.tipoMoto = tipo;
        this.manillarMoto = manillar;
        this.cilindradaMoto = cilindrada;
    }

    public void setDatosCamion(int numEjes, double cargaNeta, String tipoRemolque) {
        this.numEjesCamion = numEjes;
        this.cargaNetaCamion = cargaNeta;
        this.tipoRemolqueCamion = tipoRemolque;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoDatosGenerales.class.getName());

    /**
     * Creates new form IngresoDatosGenerales
     */
    public IngresoDatosGenerales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Datos Generales del Vehiculo");

        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Número de serie");

        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Peso");

        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Estación");

        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Año de fabricación");

        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Velocidad maxima");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoSalir.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoIngresarVeh.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(80, 80, 80)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(jLabel1))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel8)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || 
               jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || 
               jTextField5.getText().isEmpty()) {
                throw new Exception("Por favor, complete todos los campos.");
            }

            int numSerie = Integer.parseInt(jTextField1.getText().trim());
            double peso = Double.parseDouble(jTextField2.getText().trim());
            int estacion = Integer.parseInt(jTextField3.getText().trim()); 
            int anio = Integer.parseInt(jTextField4.getText().trim());
            double velMax = Double.parseDouble(jTextField5.getText().trim());

            VehiculoPersistencia<Vehiculo1> persistencia = new VehiculoPersistencia<>();
            ArrayList<Vehiculo1> lista = new ArrayList<>();
            
            try {
                persistencia.RecuperarVehiculos(lista);
            } catch (Exception e) {
            }

            Vehiculo1 nuevoVehiculo;

            switch (tipoVehiculo) {
                case "SCOOTER":
                    nuevoVehiculo = new Scooter(anio, numSerie, (int) peso, estacion, velMax,
                            false, plegable, bluetoothScooter, diametroRuedas, marcaScooter);
                    ((Scooter) nuevoVehiculo).setPorcBateria(porcBateriaScooter);
                    break;
                case "BICICLETA":
                    nuevoVehiculo = new Bicicleta(anio, numSerie, (int) peso, estacion, velMax,
                            false, tipoMotorBici, pantallaBici, tipoBici);
                    break;
                case "MOTO":
                    nuevoVehiculo = new Moto(anio, numSerie, (int) peso, estacion, velMax,
                            false, tipoMoto, manillarMoto, cilindradaMoto);
                    break;
                case "CAMION":
                    nuevoVehiculo = new Camion(anio, numSerie, (int) peso, estacion, velMax,
                            false, numEjesCamion, cargaNetaCamion, tipoRemolqueCamion);
                    break;
                default: // "AUTO"
                    nuevoVehiculo = new Auto(this.marca, this.modelo, this.placa, numSerie,
                            (int) peso, estacion, anio, velMax, this.numPasajeros);
                    break;
            }

            lista.add(nuevoVehiculo);
            
            persistencia.GuardarVehiculos(lista);

            JOptionPane.showMessageDialog(this, "¡Vehículo registrado exitosamente!");
            
            MenuTrabajador menu = new MenuTrabajador();
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en campos numéricos. Verifique los datos.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        IngresarVehiculo anterior = new IngresarVehiculo();
           anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoDatosGenerales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
