/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Excepciones.CaractInicio;
import Excepciones.SinDigitos;
import Excepciones.SinLetras;
import Excepciones.TextVacio;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class IngresoBicicleta extends javax.swing.JFrame {
    int tipo, tipomot, porcBat;
    boolean pan;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoBicicleta.class.getName());

    /**
     * Creates new form IngresoBicicleta
     */
    public IngresoBicicleta() {
        initComponents();
    }
    
    public void RevisionTextoDig(String cad) throws SinDigitos{
        int cont=0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isDigit(c)){
                cont++;
            }
        }
        if(cont>0){
            throw new SinDigitos("Este texto no puede llevar numeros.");
        }
    }
    
    public void RevisionTextoLet(String cad) throws SinLetras{
        int let = 0;
        for(int i=0;i<cad.length();i++){
            char c = cad.charAt(i);
            if(Character.isLetter(c)){
                let++;
            }
        }
        if(let>0){
            throw new SinLetras("Este texto no puede llevar letras.");
        }
    }
    
    public void RevisionTextoVacio(String cad) throws TextVacio{
        if(cad.length() == 0){
            throw new TextVacio("Escriba algo para ingresar...");
        }
    }
    
    public void Comienzo(String cad) throws CaractInicio{
        char c = cad.charAt(0);
        char t = ' ';
        if(c == t){
            throw new CaractInicio("Caracter de inicio vacio.");
        }
    }
    
    public void RevisionTextoEspeciales(String texto) throws IllegalArgumentException {  
        for (int i = 0; i < texto.length(); i++) {
            char c = texto.charAt(i);
            
            if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
                throw new IllegalArgumentException("Error: Se encontró un carácter especial '" + c + "' en la cadena.");
            }
        }
        
        System.out.println("La cadena '" + texto + "' es válida y está limpia.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        T_Tipo = new javax.swing.JTextField();
        T_TipoM = new javax.swing.JTextField();
        T_Pan = new javax.swing.JTextField();
        T_PorcBat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ingreso de Bicicleta");

        jLabel2.setText("TIpo");

        jLabel3.setText("TIpo de motor");

        jLabel4.setText("Pantalla(Si o No)");

        jLabel5.setText("Porcentaje de bateria");

        jButton1.setText("Ingresar Bicicleta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");

        T_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_TipoActionPerformed(evt);
            }
        });

        T_TipoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_TipoMActionPerformed(evt);
            }
        });

        T_Pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_PanActionPerformed(evt);
            }
        });

        T_PorcBat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_PorcBatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(T_PorcBat, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(T_Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(T_TipoM)
                                    .addComponent(T_Pan))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(T_TipoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T_Pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(T_PorcBat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void T_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_TipoActionPerformed
        try{
            tipo = Integer.parseInt(T_Tipo.getText());
            RevisionTextoLet(T_Tipo.getText());
            RevisionTextoVacio(T_Tipo.getText());
            Comienzo(T_Tipo.getText());
            RevisionTextoEspeciales(T_Tipo.getText());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_TipoActionPerformed

    private void T_TipoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_TipoMActionPerformed
        try{
            tipomot = Integer.parseInt(T_TipoM.getText());
            RevisionTextoLet(T_TipoM.getText());
            RevisionTextoVacio(T_TipoM.getText());
            Comienzo(T_TipoM.getText());
            RevisionTextoEspeciales(T_TipoM.getText());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_TipoMActionPerformed

    private void T_PanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_PanActionPerformed
        String respuesta = T_Pan.getText().trim().toLowerCase();
    
        // 2. Comparamos si es exactamente "si" o "no"
        if (respuesta.equals("si") || respuesta.equals("no") || respuesta.equals("sí")) {

            // El dato es correcto, aquí pones tu lógica para guardar el auto
            System.out.println("Respuesta válida: " + respuesta);

        } else {
            // El usuario ingresó otra cosa, mostramos un error
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: Por favor, ingrese únicamente 'si' o 'no'.", 
                "Dato inválido", 
                javax.swing.JOptionPane.ERROR_MESSAGE);

            // Regresamos el foco al campo de texto para que lo corrija
            T_Pan.requestFocus(); 
        }
    }//GEN-LAST:event_T_PanActionPerformed

    private void T_PorcBatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_PorcBatActionPerformed
        try{
            porcBat = Integer.parseInt(T_PorcBat.getText());
            RevisionTextoLet(T_PorcBat.getText());
            RevisionTextoVacio(T_PorcBat.getText());
            Comienzo(T_PorcBat.getText());
            RevisionTextoEspeciales(T_PorcBat.getText());
        }catch(SinLetras e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(TextVacio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(CaractInicio e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_T_PorcBatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoBicicleta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T_Pan;
    private javax.swing.JTextField T_PorcBat;
    private javax.swing.JTextField T_Tipo;
    private javax.swing.JTextField T_TipoM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
